export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const TKAN_ROUTE = '/tkan'
export const ABOUTUS_ROUTE = '/AboutUs'
export const UIKIT_ROUTE = '/uikit'